# Generated by Django 4.2 on 2023-08-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryBig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50, unique=True)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=200, unique=True),
                ),
            ],
            options={"verbose_name_plural": "CategoriesBig",},
        ),
        migrations.CreateModel(
            name="CategorySmall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorybig",
                    models.CharField(default="", max_length=50, unique=True),
                ),
                ("name", models.CharField(default="", max_length=50, unique=True)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=200, unique=True),
                ),
            ],
            options={"verbose_name_plural": "CategoriesSmall",},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("month", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("price", models.IntegerField(max_length=30)),
                ("unit", models.CharField(max_length=10)),
                (
                    "main_image",
                    models.ImageField(blank=True, upload_to="helpyou/files/%Y/%m/%d"),
                ),
                (
                    "sub_image1",
                    models.ImageField(blank=True, upload_to="helpyou/files/%Y/%m/%d"),
                ),
                (
                    "sub_image2",
                    models.ImageField(blank=True, upload_to="helpyou/files/%Y/%m/%d"),
                ),
                (
                    "sub_image3",
                    models.ImageField(blank=True, upload_to="helpyou/files/%Y/%m/%d"),
                ),
                (
                    "categorybig",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helpyou.categorybig",
                    ),
                ),
                (
                    "categorysmall",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helpyou.categorysmall",
                    ),
                ),
            ],
        ),
    ]
