# Generated by Django 4.2 on 2023-08-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpyou", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="price", field=models.IntegerField(),
        ),
    ]
