# Generated by Django 4.2 on 2023-08-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("helpyou", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorysmall",
            name="categorybig",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="helpyou.categorybig",
            ),
        ),
    ]
