# Generated by Django 4.2 on 2023-08-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpyou", "0004_cart_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="card",
            field=models.CharField(default="3000", max_length=30),
        ),
    ]
